# .github/workflows/update-citations.yml
name: update-citations
on:
  schedule: # run twice a day at 06:00 and 18:00 CET
    - cron: "0 4 * * *"  # 06:00 CET
    - cron: "0 16 * * *" # 18:00 CET
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Pull latest numbers from SerpAPI
        run: |
          pip install serpapi
          python build_json.py \
                 "${{ secrets.SERPAPI_KEY }}" MI0C9mAAAAAJ

      - name: Commit the new JSON
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "bot@example.com"
          git config --global user.name  "cite-bot"
          git add ./citations.json
          git commit -m "daily citation refresh" || echo "no change"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
